            - name: DesigniteJava Action
  # You may pin to the exact commit or the version.
  # uses: DesigniteTools/DJAction@b52255133c5742a104cfad177775edb22bd4c92c
  uses: DesigniteTools/DJAction@v2.0
  with:
    # Personal access token
    PAT: # optional, default is No PAT provided
    # Designite license key - optional
    D_KEY: # optional, default is No key
          
